#!/bin/bash

readonly IMAGE="progrium/consul"

main() {
	local container_id="$1"; shift
	local port="$1"; shift
	local path="$1"; shift
	local opts="$@"
	
	local ip="$(docker inspect -f "{{.NetworkSettings.IPAddress}}" $container_id)"
	local curl_cmd="curl \
		--include \
		--silent \
		--show-error \
		--fail \
		--retry 2 \
		$opts \
		http://$ip:$port$path"
	docker run --rm --net container:$container_id --entrypoint "/bin/bash" $IMAGE -c "$curl_cmd"
}

main $@